apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
 # namespace: kube-ops
  labels: 
    name: pv-01 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    #FIXME: use the right IP
    server: 192.168.3.175
    path: "/data/nfs"
