apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: kube-ops
  labels:
    name: pv-01
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  resources: 
    requests: 
      storage: 4Gi
