kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx-controller
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.11
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volume-root
              mountPath: /usr/share/nginx/html
              subPath: nginx/www
      volumes:
        - name: volume-root
          persistentVolumeClaim:
            claimName: jenkins-pvc
---
